
    ##There's a bunch of code here that I was going to impliment later, nothing as simple as DDLC's code,
    ##shit that's a lot more involved and actually done in python. If you want to take a stab at it you can
    ##but I'm not expecting you to.
    ##most of the comments you'll see below are in reference to that, if it's not the POV changes.
label sayoriroute2:
    "It's morning."
    "As I suddenly feel the sunlight hit my eyes, I also notice a light breathing hit my shirt, and look down."
    "It's Sayori."
    "She's got her head against me, using me as a pillow, resting there solumnly."
    "Wait, but why is she?"
    "I think to myself for a second."
    "{i}Oh.{/i}"
    "{i}Oh, right.{/i}"
    "Well..."
    "That's certainly one way to celebrate 4 months of being together."
    "I'm not cognizant enough of last night's events to know who should be blamed for it."
    "But, whatever, the past is the past."
    "She's... rather peaceful, like this."
    "I gently put my hand on her head."
    "She lightly stirs, but shows no signs of awakening."
    "Well, it'll be kind of difficult to get out of here..."
    "She did say she was a really heavy sleeper though."
    "I slowly attempt to move her from her position, and bring her to the side of me."
    "Lucky, she doesn't even show a subconscious sign that she's noticed."
    "I get out of bed, yawning quietly and walking out of my room."
    "I walk downstairs to the kitchen, and I'm about to grab a few eggs, when I realize something."
    "Sayori's told me that she has three favorite things in this world."
    "1: Me."
    "2: Sleep."
    "3, and the more pressing issue at hand: Food."
    "So, knowing this..."
    "I'll combine her three favorite things, and make her breakfast in bed!"
    
    
    "It's yet again another Sunday."
    "Unusually, Natsuki decided to text me."
    n "Hey, can I hang out with you guys today?"
    "I show the text message to Sayori."
    "Naturally, she's overjoyed by the idea."
    s "Yay!"
    s "My best friend and boyfriend are going to hang out together!"
    mc "Best friend?"
    s "Yup! Now that we're dating, Natsuki gets to be my best friend!"
    "I mean, I guess that does make sense." 
    mc "Hey, haven't you know Natsuki longer than me?"
    "Sayori takes a moment to think."
    s "No, I don't think so. I met her in fifth grade."
    mc "Fifth grade? Really?"
    s "Yessir!" 
    s "We were both looking for coins under the vending machine!"
    mc "Well, I guess that makes sen- {i}what?{/i}"
    s "Yeah! I remember it like it just happened..."
    #scene change; Sayori's perspective employed here, don't code in her sprite.
    "Okay, so, [player] wants me to get him a cookie, and I'll get some apple juice..."
    "I open my mini purse and stick some coins into the vending machine."
    "One of the coins starts to slip out of my hands, and it falls."
    "It bounces off my shoe and directly under the vending machine."
    s "Aww, man!"
    "I get down on the floor and start attempting to snatch it up."
    "However, I feel another hand or something grab for the coin as well."
    "I'm startled, and have to stop myself from screaming."
    "To my surprise, the other actually does scream, and the hand quickly retracts."
    "Oh god, I don't have to look over there, do I?"
    "Guess I've got no other choice..."
    "I slowly look over, awaiting the monster on the other side..."
    "Only to see some bright pink hair staring back at me."
    s "Hello?"
    n "H-hi..."
    "Realizing it's a small girl and not a hideous monster, I extend a hand to her."
    s "Hello!"
    s "I'm Sayori! What's your name?"
    "She at first flinches, but eventually reaches to shake it."
    n "I'm Natsuki. Nice to meet you, Sayori..."
    s "What were you doing under there?"
    "She turns her head away from me."
    n "I wasn't fishing for coins or something, if that's what you think..."
    "I smile."
    "This girl's a really bad liar."
    "I think we'll get along just fine."
    #back to mc's point of view
    s "And that's how we met. It's been a growing friendship ever since."
    mc "Wow."
    "I realize that's probably a fond memory for Sayori, really."
    "Before I can give further comment, or ask how she met some of the others, a mass of pink shows up at our door."
    "Sayori goes to answer it."
    "Before they come in, they converse."
    "The two say some things to each other I can't really make out."
    "A look appears in both of their eyes, and they walk over to me."
    n "So, me and Sayori thought over it..."
    n "and we want to play Never Have I Ever for the first game tonight."
    n "But, to make it interesting... the loser has to wear whatever the other two wants him- or, wants them, to."
    "I roll my eyes."
    mc "Are we seriously doing this?"
    "I don't know why Sayori thought inviting Natsuki over one day was a good idea."
    "I mean, of all the games to play, 'Never Have I Ever'?"
    "It's like she's asking for all 3 of us to be embarrassed."
    s "Come on, it'll be fun."
    n "Pfft, clearly he's just chicken. It's alright, you don't have to play if you're scared."
    "Oh, is {i}that{/i} how she wants to play it?"
    mc "Scared? Me?"
    mc "Keep Dreaming. I'm in."
    s "Yaaaaay!"
    "Sayori wraps her arms around me, happy."
    "I swear, it's the little things that make her happy."
    n "Everyone know the rules?"
    "Sayori and I nod."
    "With that, the three of us stand shoulder to shoulder at the end of the hallway."
    "Natsuki seems to have chosen an extra long playing field."
    n "Anyone want to start?"
    "Seeing my easy advantage, I step forward."
    mc "Never have I ever stayed up until three AM to finish a video game."
    "Natsuki chuckles."
    n "How do you get any sleep, Sayori?"
    s "It's okay! I don't sleep very early normally, anyway..."
    n "Whatever. I guess that means it's my turn."
    n "Never have I ever done a cartwheel!"
    "Natsuki and Sayori both take a step forward."
    "I feel like she's toying with me."
    "Sayori goes next."
    s "Never have I ever..."
    s "Stolen a cookie from Natsuki!"
    "She walks forward, proud of herself."
    n "Hey! That's against the rules!"
    n "... isn't it?"
    mc "I don't know. Seems perfectly legal to me."
    mc "I smile."
    mc "It may put me behind Sayori, but seeing the slight anger on Natsuki's face is worth it."
    n "Alright, fine. [player], it's back to you."
    mc "Sweet."
    mc "Never have I ever..."
    "I stop to think."
    "I don't want to pull the masturbation card just yet..."
    "Partly because I have a functional sense of shame, and partly because I don't want to learn something about these two that I didn't want to know."
    "I need something else specific to my gender, maybe..."
    mc "...used a urinal."
    "I take a step forward, smug."
    n "Oh yeah, well, never have I ever been in a woman's restroom!"
    "Natsuki and Sayori both step forward."
    mc "You realize that this still puts Sayori in the lead, right?"
    n "..."
    "I hear what i assume to be a low growl out of Natsuki."
    "I can tell I'm getting to her."
    n "Sayori, your turn."
    s "Never have I ever played a guitar!"
    "Sayori alone steps forward."
    mc "Sayori, I've never seen your guitar..."
    n "Neither have I..."
    s "Ehehe... I probably shoved it under my bed, or into a closet..."
    "I shrug it off and take my turn without prompting."
    "Never have I ever kept my hair dye-free."
    "All three of us step forward."
    "Wait, all three of us?"
    "Sayori and I both stare at Natsuki."
    n "What? It's completely natural, I swear!"
    "Well, that's a waste of a turn."
    "Natsuki realizes that this was a target attack and decides to fire back."
    n "Never have I ever read a Manga 3 times!"
    "Natsuki alone steps forward, putting me behind her and the now tied Sayori."
    "Sayori, realizing this, tries to come up with something."
    "I pity her, as she was never really the competitive type."
    "Although, I guess that's a good thing."
    "Her attitude seems a lot more carefree than mine or Natsuki's."
    "I guess ignorance truly is bliss."
    s "Never have I ever failed PE class!"
    "She takes a step forward, a bit more proud than she needs to be."
    mc "You don't seem to lack athletic ability, Sayori."
    s "No, but it was my first period class."
    s "They don't let you in late..."
    "That makes a bit more sense."
    "Natsuki and I stay back, putting Sayori back in the lead. Then Natsuki, then myself."
    mc "Never have I ever swallowed a spider!"
    "I strut to Natsuki's position, confident."
    s "Eek!"
    "Natsuki's face is one of pure disgust."
    mc "I lost a bet when I was nine. I guess it help me out, in the end."
    n "Boys are so gross."
    "Natsuki begins scheming."
    n "Never have I ever put on lipstick!"
    "All three of us step forward."
    n "Wha- really?"
    "Natsuki looks at me."
    mc "Different bet this time."
    mc "You never said where the lipstick was applied."
    mc "I had to draw a rather phallic shape on my forehead and leave it on for three hours."
    n "..."
    s "Anyway!"
    s "Never have I ever been shoved in a locker!"
    "Both Sayori and Natsuki step forward."
    n "Keep that up Sayori. Keep the eagle in its nest."
    "Wait, what?"
    "What kind of expression is that?"
    "It almost sounds like a code word..."
    "Ah, I'm sure it's nothing."
    "What to do next...?"
    "Natsuki basically stole my wank card."
    "How about..."
    mc "Never have I ever been locked in a closet for an hour!"
    "Me and Sayori step forward."
    "Back on equal footing with Natsuki. Sayori now has a two-step lead."
    "Hopefully, that's not going to come back to bite us later."
    "We're now almost through the hall."
    n "Never have I ever... gotten a cupcake thrown in my face!"
    "Sayori and Natsuki both step forward."
    mc "... is there a story here?"
    s "Ooh, Ooh, can I tell it?"
    "Before either Natsuki and I can answer, Sayori starts up..."
    #POV changes again to sayori.
    n "Well, here they are!"
    n "I wanted to thank you for being my friend by making you these, so... here."
    "Aww, this is sweet!"
    "Natsuki brought me some cupcakes for our sleepover today!"
    s "Thank you, Natsuki!"
    "I say, and grab one."
    "I take a bite. It's... really good, actually."
    s "I like it!"
    n "I knew I was a good baker!"
    s "It could be better, though..."
    n "Really?"
    "Natsuki takes a bite out of her own cupcake."
    n "How?"
    s "Simple."
    "I then take the cupcake and push it in her face."
    s "It doesn't have enough Natsuki in it!"
    n "Hey!"
    "Natsuki laughs, and reacts by getting revenge using her own cupcake, and my face."
    "She then grabs another one from her tray and starts chasing me around with it."
    "I run, but all my laughing catches up to me and I eventually double over."
    "She takes it and puts it on top of my head like a hat."
    s "Woah, Natsuki..."
    n "I didn't go too far, did I?"
    s "...this cupcake makes a really good hat!"
    "We both laugh."
    #PoV is back to normal---
    n "Hey, I never said that last line!"
    s "You totally did!"
    mc "I hate to cut the theatrics short, but it's your turn, Sayori."
    s "Oh yeah!"
    s "Never have I ever gotten a cupcake shoved in my hair!"
    "Sayori takes a three step lead."
    n "Sayori, come on, eagle in the nest!"
    s "What? He's still behind."
    n "DON'T SAY THAT OUT LOUD!"
    "...I feel like they're conspiring."
    mc "What's going on?"
    n "Okay so..."
    n "We may or not have come up with a plan to put you in last..."
    n "Because we really wanted to see what you looked like in one of Sayori's dresses."
    "... seriously?"
    "That's the game plan?"
    mc "Well, now I have to win."
    n "Not if I have anything to say about it!"
    "Natsuki doesn't know the mistake she's made putting my dignity on the line."
    mc "Alright, let's play that game."
    mc "Never have I ever..."
    mc "Read a hentai doujin!"
    "All 3 of us step forward."
    "..."
    mc "..."
    n "..."
    s "..."
    "A powerfully awkward silence fills the room."
    s "I was... curious one day, people talk about them in chat rooms all the time, so..."
    mc "I do it... rarely, but sometimes..."
    "Natsuki refuses to explain herself as I and Sayori do. She instead shoots me a look."
    mc "Desperate times, Desperate measures." 
    n "Yeah, yeah."
    n "Never have I ever slept in a doghouse!"
    "Natsuki alone steps forward, beginning to close the gap between her and Sayori."
    s "Never have I ever won a game of Never Have I Ever!"
    "Sayori takes a step forward and completes the game."
    "I don't have the heart to tell her that's probably against the rules."
    "At this point, I'm three steps away from the goal. Natsuki is two steps away."
    mc "Never have I ever taken items from the top shelf of a store!"
    "I step forward."
    n "Ah come on, that was low!"
    mc "You know a lot about low, don't you Natsuki?"
    n "Oh yeah? Never have I ever looked for coins under a vending machine!"
    "Damn, that one had exposition to it, too."
    "Natsuki takes her step forward." 
    "I've got to make sure this next one is perfect..."
    "Never have I ever slept next to Sayori!"
    "I made sure my wording was perfect as not to imply anything lewd."
    "Me and Natsuki are neck and neck..."
    "Until she takes a step forward."
    "I pause."
    n "Be careful with your wording."
    n "I've slept next to Sayori too. We've had sleepovers before."
    n "Not in the same bed, but it still counts!"
    "... my own wording trick got me."
    "I stand there, one step from the goal, Natsuki and Sayori having already crossed it."
    "Natsuki puts on a face so smug it's blinding."
    n "Well, Sayori, you know what that means!"
    n "Go pick out your favorite dress!"
    s "I'll be right back!"
    "Great..."
    "Sayori comes back, dress in hand, and I excuse myself to the restroom to put it on."
    "As soon as I come out, a camera flash blinds my vision."
    mc "Hey, no one said anything about pictures!"
    s "Come on, [player]! Can I just put some make up on you? You'd look so cute!"
    n "Stand still, you're making the photo blurry! Remember, you've gotta wear that the rest of the night!"
    "Good grief..."
    
    scene bg club_day
    with dissolve_scene_half
    play music t4
    m "Alright, Sayori, would you like to spin next?"
    "Sayori cheerfully grabs the bottle in the center of us five and twirls it around to the best of her ability."
    "The moment Yuri decided to pull out a bottle of wine, I knew things would end up getting weird."
    "A game of drunk spin-the-bottle, though, was not what I had in mind."
    "Monika didn't even put that much effort into preventing a case of underage drinking."
    "As soon as she noticed Yuri, Sayori, and Natsuki already half drunk she just had to tell me about how wrong and outrageous it is."
    "I'd perhaps be a bit less salty about it if she didn't drink the last bit behind my back."
    "So now I'm the only sober person in a classroom of drunk high school girls."
    n "OOOOOOOH, IT LANDED ON [player]! YOU KNOW WHAT THAT MEAAAANS~"
    "Natsuki exclaims in a sing-song voice. It's clear she can't help to keep her voice down."
    "I look down to see that the bottle is, in fact, pointed right at me."
    "Natsuki tries to pull me up, and fails completely."
    "I get up, and she musters some kind of strength to push me into the closet."
    "Yuri does the same to Sayori, and closes the door behind us."
    n "Don't you touch any of my manga!"
    "I look at Sayori as best I can."
    "Strangely, there really isn't that same drunken look in her eyes that I see from the other girls."
    "I wait for her to try to do something or other while we're in this closet, but she just sits down."
    s "So, seven minutes in here, huh?"
    "I pause."
    "That sentence was pretty much completely coherient."
    mc "Sayori..."
    mc "You don't really sound very drunk..."
    s "I'm not drunk, silly!"
    s "I kinda hate the taste of alcohol..."
    "..."
    "That does make a fair bit of sense."
    mc "You just faked it to fit in, didn't you?"
    s "Ehehe~!"
    s "You just know me way too well, [player]!"
    mc "I suppose I'm not quite surprised, either."
    "I stop leaning against a bookshelf and take a seat next to her."
    mc "So, what do you think?"
    s "Hmm?"
    mc "About this whole mess."
    mc "Yuri, getting the whole class drunk."
    mc "Except for me and you, I suppose."
    "She takes a minute to think."
    s "Well..."
    s "It's not really a good thing..."
    "Sayori's mood suddenly becomes a bit more somber."
    s "But I don't want to be the person who kills the fun for everyone, you know?"
    s "I just hope they don't start doing it too much..."
    "I shake my head."
    mc "Nah, I don't think this'll be a regular thing."
    mc "Once Monika comes to her senses, she'll put an end to this."
    s "Hmm."
    s "Welp, whatever it happens, we still have some time left in here."
    mc "Yeah."
    mc "..."
    mc "Wanna make out?"
    "Sayori immediately blushes."
    "I could swear I heard a sqeak."
    s "W-what?"
    "I can't help but chuckle at her reaction."
    mc "Relax, relax. I'm messing with you."
    s "Oh."
    "I could swear she muttered something under her breath."
    s "NotthatIwouldmind..."
    "I can't quite tell what it is, though."
    mc "Hey, Sayori..."
    s "Yes, that's me."
    "I grab a box from the bottom of one of the shelves."
    "I put my arm on top of it, perpendicular to the box's surface."
    mc "Well?"
    s "..."
    s "You want to arm wrestle?"
    "Sayori seems puzzled."
    mc "Why not, eh?"
    s "Alright, if you say so."
    "Her arm interlocks with mine."
    mc "Three... two... one..."
    "The competition begins."
    #impliment the game system here, have it rely on players smashing their spacebar
    #Win text:
        "I was going a bit easier on her, but it still wasn't too much of a challenge."
        "I easily overpower Sayori and her arm hits the crate."
        s "WOW!"
        s "You beat me so quick!"
        s "You must be super strong, [player]!"
        s "Which is weird, because I never see you do anything physical..."
        s "Actually, looking at your left arm, it looks a lot weaker than this one..."
        mc "AH, UM, ANYWAY!"
    #Loss text:
        "This power!"
        "Sayori is doing this?"
        "My arm can barely hold out against her."
        mc "Grrr..."
        "I can't help but let some grunts slip out."
        "It falls with little resistance."
        mc "Sayori... how..."
        "She didn't seem to register my shock."
        s "Aw come on, stop going easy on me!"
        s "I can handle it, promise!"
        mc "Y-yeah, going easy on you..."
        mc "I guess I'll have to stop doing that..."
        "I can't hear a hint of sarcasm or pride in her voice."
        "Is she not aware of her own stregth?"
        "Or am I just {i}that much{i} of a wimp?"
    mc "L-lets play something else."
    s "Okay!"
    s "What would you like to play?"
    mc "Hmm..."
    "I case the room."
    "I want to avoid tests of stregth to the best of my ability."
    s "Oh, here, I know what we could do..."
    "Sayori gets up from her seat next to me and sits down on my lap."
    "Her legs stretch to my right."
    "She wraps her arms around my torso and lays her head against my chest."
    "I wrap my arms around her body."
    s "Well, I'm going to take a nap."
    mc "A nap?"
    "Honestly, that's par for the course as far as Sayori goes."
    "Still, what the hell does she expect me to do?"
    s "Ehehe~"
    s "Your heart is beating so fast..."
    "I wasn't concious of it until she brought it up, but she's right."
    "I don't for the life of me understand why this has me so excited."
    "Maybe I'm just happy?"
    "Something is oddly cozy about this..."
    "I look down to see Sayori's chest rhythmically moving up and down."
    "Her eyes are closed."
    "That was quick."
    "Well, nothing better to do except follow suit, I guess."
    "I close my eyes as well."
    "..."
    "..."
    n "Hey, loooook, they're asleepin'..."
    s "Mmmm... huh?"
    "Damn it, and I was just starting to fall to rest too."
    "I sense the light from the door shine through and I open my eyes."
    "Natsuki, Yuri, and Monika are all watching from outside."
    y "Aha... for the past hourrr..."
    "Yuri and Natsuki yet still have slurred speech."
    "Wait... did Yuri just say \"past hour\"?"
    mc "Did you guys leave us in here for an hour???"
    n "We heard... huhuhuh... {i}grunting{i} coming from therrrre~"
    n "So weeeee didn't open it."
    "Grunting?"
    "What the hell is she-- {i}Oh.{i}"
    mc "Goddammit, no, we were just arm wrestling?"
    y "AHahahahhahaha! Arm Wrestling! Oh Boy..."
    "Crap..."

label natsukiroute2:
    scene bg club_day
    with dissolve_scene_full
    play music t2
    m "5 cards each!"
    "I still don't know how the hell we've gotten in this situation."
    "Isn't gambling against the school rules anyway?"
    "Natsuki pulls out a set of poker chips."
    "Where she got them, I have no idea, although they have her surname written on the packaging."
    n "60 Chips total!"
    n "There are 30 cupcakes in total, meaning each 2 chips is worth one cupcake."
    "She motions to the fluffed pastries that sit on a different desk."
    "She made them for a party originally, but she somehow or other didn't get to go to it."
    "So instead, she decided she wants to bet them in a game of poker."
    "The weirdest part is actually the fact that everyone else agreed to this."
    "Monika most of all, talk about a responsible club leader..."
    n "Now, since I brought in the cupcakes, I guess it's up to me to deal."
    s "Hey! How do we know you aren't cheating?"
    m "Sayori's right. We should do it the way any poker player does it."
    m "We all draw a card, from the top of the deck. Whoever gets the higher card goes first."
    m "Sayori, you brought the cards, right?"
    s "Yep!"
    "Sayori throws the box onto the table."
    y "I'll draw first, then."
    "Yuri sheepishly draws a card from the deck."
    "The rest of us proceed to do the same."
    "Somehow, Sayori got the ace of clubs, which was the best card of the group."
    m "Now Sayori, this means you get to deal, or choose who to deal."
    "May I suggest myself as a willing and capable candidate?"
    s "Actually, Monika, I think I'll deal for this game."
    "She seems... almost miffed, but ultimately accepts this fact."
    "Sayori shuffles, and for the sake of time we have Natsuki cut the deck."
    "Natsuki gives us each 12 chips, and the bow-clad girl to my left distribute the cards."
    "However... she doesn't seem to be dealing them the way anyone else would."
    "She's saving the first card for herself every time and then dealing for the other four of us."
    n "Sayori, you darned cheat!"
    s "Hmm?"
    "Sayori stops dealing."
    n "You're not gonna get you sleight of hand tricks past us!"
    s "Sleight of hand?"
    n "You're saving the first card for yourself every time!"
    n "Did you think we wouldn't notice?"
    s "But that's how you're supposed to do it, right?"
    "Natsuki's face goes from anger to slight confusion."
    s "That's how I've always seen it in the movies. The guy who deals always does it like this."
    "I put a hand on Sayori's shoulder."
    mc "Sayori..."
    mc "Just deal the top card every time, please."
    s "Okay!"
    mc "Now that we've got that sorted..."
    mc "Let's OPEN THE GAME!"
    "Natsuki sits down, and we get all 5 of our cards."
    mc "I'll open with 1 chip."
    "I throw one of the blue striped tokens into the center. Everyone else does the same."
    "We all take a chance to look at our cards."
    m "I'll raise the pot by 4 chips."
    "Monika slides 4 more of her chips into the center."
    "She has a satisfied look on her face."
    "I suppose I'll--"
    choice:
        "Fold":
            mc "Fold."
            s "Fold."
            y "Fold."
            n "Call."
            "Natsuki puts her 5 chips into the center."
            "She then swaps out three of her cards, and two of Monika's."
            "Both of them sit there, expressionless. Possibly out of fear, or maybe they just have really good poker faces."
        "Call":
            mc "Call."
            "I put 4 of my chips into the center."
            "Natsuki decides to do the same, then Sayori."
            "As each of us does so, the look on her face seems less and less satisfied."
            s "Anyone want to trade in their cards?"
    "The game's almost over now."
    "Natsuki and I are the only ones with any chips on the table."
    "Her with 20, me with variable."

    #remeber to put the variable here fuckhead
    #also extend the code so there's more gameplay than this 
    n "Hey, [player], just so you know..."
    n "I'm not going to go easy on you."
    mc "Is that so?"
    mc "Well, well. Let's do something risky, then."
    "She deals us both our cards."
    "I don't even look at mine as I place my bet."
    mc "All in!"
    #set up a check to see if your chip number is greater than natsuki's or not
    #if not:
        n "Every chip you've got, huh?"
        n "Suit yourself."
        n "I'll match you with your variable."
        #put the variable in
    #if so:
        n "Damn."
        n "Alright, then count me as all in, too."
        n "This really is the all or nothing game, isn't it?"
        #make sure the player doesn't get an ace so Natsuki always wins in both scenarios
    n "Four of a kind... Aces."
    "Natsuki puts her cards down, smug."
    "W-what the hell? That's the strongest hand in the game!"
    n "Sorry, [player]."
    n "Luck's sided with me, today!"
    "Natsuki, beaming, takes all the chips for herself."
    "Why the little..."
    s "Did we win, Natsuki?"
    "Sayori's head pops out from under the table."
    "Natsuki's eyes go wide."
    n "Y-you..."
    n "YOU IDIOT! YOU WEREN'T SUPPOSED TO SAY THAT! ARE YOU STUPID OR SOMETHING? NOW EVERYONE KNOWS WE CHEATED!"
    "Sayori, in fear, drops all the cards she was holding."
    "All of them aces."
    "Wait a minute, so they were..."
    mc "Natsuki..."
    "She takes a minute off from smacking Sayori upside the head and looks at me."
    "The fear on Sayori's face becomes mirrored on hers, and she grabs Sayori by the hand and runs out of the classroom."
    "Dammit, she isn't getting away that easy..."
